rover_denso:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Velocity Controllers ---------------------------------------
  base_differential_velocity_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel: ['left_wheel1_hinge', 'left_wheel2_hinge']
    right_wheel: ['right_wheel1_hinge', 'right_wheel2_hinge']
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    enable_odom_tf: false
    odom_frame_id: "/odom"
    wheel_radius: .118
    wheel_separation: 0.366
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier: 1.0
    base_frame_id: chassis
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.1   # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.05   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 0.1   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 1.0   # rad/s^2
    allow_multiple_cmd_vel_publishers: false


  # Position Controllers ---------------------------------------
  denso_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    # gains:
    #   joint_1: {p: 232.0, i: 20.0, d: 4.0}
    #   joint_2: {p: 232.0, i: 20.0, d: 4.0}
    #   joint_3: {p: 232.0, i: 20.0, d: 4.0}
    #   joint_4: {p: 232.0, i: 20.0, d: 4.0}
    #   joint_5: {p: 232.0, i: 20.0, d: 4.0}
    #   joint_6: {p: 232.0, i: 20.0, d: 4.0}
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_1: {trajectory: 0.157, goal: 0.01}
      joint_2: {trajectory: 0.157, goal: 0.01}
      joint_3: {trajectory: 0.157, goal: 0.01}
      joint_4: {trajectory: 0.157, goal: 0.01}
      joint_5: {trajectory: 0.157, goal: 0.01}
      joint_6: {trajectory: 0.157, goal: 0.01}
    stop_trajectory_duration: 0.2
    state_publish_rate:  25
    action_monitor_rate: 10
    required_drive_mode: 7


